apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: get-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: get-api
  template:
    metadata:
      labels:
        app: get-api
    spec:
      containers:
      - name: flask-api
        image: hanaasous1/character-occurrence-api
        ports:
        - containerPort: 5000
---

apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    app: get-api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000
